<<<<<<< HEAD
# Generated by Django 3.1.5 on 2021-01-11 18:58

from django.db import migrations, models
=======
# Generated by Django 3.1.5 on 2021-01-10 14:16

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 0c08b3206d4440126adf0d93080c545a706a0493


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
=======
            name='RentalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('rentalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rentalapp.rentalmodel')),
                ('house_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
            bases=('rentalapp.rentalmodel',),
>>>>>>> 0c08b3206d4440126adf0d93080c545a706a0493
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('device_id', models.IntegerField()),
            ],
=======
                ('rentalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rentalapp.rentalmodel')),
                ('user_id', models.IntegerField()),
                ('device_id', models.IntegerField()),
            ],
            bases=('rentalapp.rentalmodel',),
>>>>>>> 0c08b3206d4440126adf0d93080c545a706a0493
        ),
        migrations.CreateModel(
            name='House',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner_id', models.IntegerField()),
                ('address_id', models.IntegerField()),
            ],
=======
                ('rentalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rentalapp.rentalmodel')),
                ('name', models.CharField(max_length=200)),
                ('owner_id', models.IntegerField()),
                ('address_id', models.IntegerField()),
            ],
            bases=('rentalapp.rentalmodel',),
>>>>>>> 0c08b3206d4440126adf0d93080c545a706a0493
        ),
        migrations.CreateModel(
            name='HouseProperties',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.IntegerField()),
                ('property_id', models.IntegerField()),
                ('value', models.CharField(max_length=255)),
            ],
=======
                ('rentalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rentalapp.rentalmodel')),
                ('house_id', models.IntegerField()),
                ('property_id', models.IntegerField()),
                ('value', models.CharField(max_length=200)),
            ],
            bases=('rentalapp.rentalmodel',),
>>>>>>> 0c08b3206d4440126adf0d93080c545a706a0493
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('reference_id', models.IntegerField()),
                ('logged_in_at', models.DateField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
=======
                ('rentalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rentalapp.rentalmodel')),
                ('mobile', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('reference_id', models.IntegerField()),
                ('logged_in_at', models.DateField()),
>>>>>>> 0c08b3206d4440126adf0d93080c545a706a0493
                ('otp', models.IntegerField()),
                ('otp_expiry', models.DateField()),
                ('status', models.IntegerField()),
            ],
<<<<<<< HEAD
=======
            bases=('rentalapp.rentalmodel',),
>>>>>>> 0c08b3206d4440126adf0d93080c545a706a0493
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('index', models.IntegerField()),
            ],
=======
                ('rentalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rentalapp.rentalmodel')),
                ('name', models.CharField(max_length=200)),
                ('index', models.IntegerField()),
            ],
            bases=('rentalapp.rentalmodel',),
>>>>>>> 0c08b3206d4440126adf0d93080c545a706a0493
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
            ],
=======
                ('rentalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rentalapp.rentalmodel')),
                ('user_id', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
            ],
            bases=('rentalapp.rentalmodel',),
>>>>>>> 0c08b3206d4440126adf0d93080c545a706a0493
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('house_id', models.IntegerField()),
            ],
=======
                ('rentalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rentalapp.rentalmodel')),
                ('user_id', models.IntegerField()),
                ('house_id', models.IntegerField()),
            ],
            bases=('rentalapp.rentalmodel',),
>>>>>>> 0c08b3206d4440126adf0d93080c545a706a0493
        ),
    ]
