# Generated by Django 3.1.5 on 2021-01-13 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.house'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.profile'),
        ),
        migrations.AlterField(
            model_name='house',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.profile'),
        ),
        migrations.AlterField(
            model_name='houseproperties',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.address'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.house'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentalapp.profile'),
        ),
    ]
