# Generated by Django 3.1.5 on 2021-01-12 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='House',
            new_name='Houses',
        ),
        migrations.RemoveField(
            model_name='address',
            name='house_id',
        ),
        migrations.RemoveField(
            model_name='houseproperties',
            name='property_id',
        ),
        migrations.AddField(
            model_name='address',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='houses', to='rentalapp.houses'),
        ),
        migrations.AddField(
            model_name='houseproperties',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='rentalapp.properties'),
        ),
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
